listings/urls.py
from . import views
from django.urls import path
from .views import ListingsListView
from .views import ListingsDetailView

urlpatterns = [
    # path('/li',views.listing,name='list'),
    path('', ListingsListView.as_view(), name='listings'),
    path('<int:pk>/', ListingsDetailView.as_view(), name='listing'),
    path('search/',views.search,name='search')
]

pages/urls.py
from pages import views
from django.urls import path

#from pages.views import Home
urlpatterns = [
   path('', views.home,name='home'),
   path('about/',views.about,name='about'),
    #path('',Home.as_view(),name='home'),
    #path('about/',About.as_view(),name='about')

]

web_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('listings/',include('listings.urls')),
    path('contact/',include('contact.urls')),
    path('accounts/',include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

listings/models.py
from django.db import models
from datetime import datetime
from realtors.models import Realtor
class Listings(models.Model):


    realtor=models.ForeignKey(Realtor,on_delete=models.DO_NOTHING)
    title=models.CharField(max_length=200)
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=50)
    zipcode=models.CharField(max_length=10)
    description=models.TextField()
    bedrooms=models.IntegerField()
    bathrooms=models.DecimalField(max_digits=2,decimal_places=1)
    garage=models.IntegerField(default=0)
    sqft=models.IntegerField()
    lot_size=models.DecimalField(max_digits=5,decimal_places=2)
    price=models.IntegerField(default=False)
    is_published=models.BooleanField(default=True)
    list_date=models.DateTimeField(default=datetime.now)
    photo_main=models.ImageField(upload_to='photos/%y/%m/%d')
    photo_1 = models.ImageField(upload_to='photos/%y/%m/%d',blank=True)
    photo_2 = models.ImageField(upload_to='photos/%y/%m/%d',blank=True)
    photo_3 = models.ImageField(upload_to='photos/%y/%m/%d',blank=True)
    photo_4 = models.ImageField(upload_to='photos/%y/%m/%d',blank=True)
    photo_5=models.ImageField(upload_to='photos/%y/%m/%d',blank=True)
    photo_6 = models.ImageField(upload_to='photos/%y/%m/%d',blank=True)
    def __str__(self):
        return self.title







# Create your models here.

listings/views.py
from django.shortcuts import render
from django.utils import timezone
from listings.models import Listings
from django.views.generic import ListView, DetailView
from .search import bedroom_choices,price_choice,state_choices

"""
def listings(request):
    listings=Listings.objects.all()
    context={'listings':listings}

    return render(request, 'listings/listings.html',context)
def listing(request):
    return render(request, 'listings/listing.html')
"""
def search(request):
    listings=Listings.objects.order_by('-list_date')
    #hetiing information from from by using request.GEt

    #keywords

    if 'keywords' in request.GET:
            print(request.GET)
            keywords =request.GET['keywords']
            if keywords:
                listings=listings.filter(discription__icontains=keywords)
    if 'state' in request.GET:
            state =request.GET['state']
            if state:
                listings=listings.filter(state__iexact=state)
    if 'bedrooms' in request.GET:
            bedrooms =request.GET['bedrooms']
            if bedrooms:
                listings=listings.filter(bedrooms__iexact=bedrooms)
    if 'city' in request.GET:
            city =request.GET['city']
            if city:
                listings=listings.filter(city__iexact=city)
    if 'price' in request.GET:
            price =request.GET['price']
            print(type(price))
            if price:
                listings=listings.filter(price__lte=price)



    context = {"listings":listings,
               "state_choices": state_choices,
               "bedroom_choices": bedroom_choices,
               "price_choice": price_choice,
               "values":request.GET
               }
    return render(request,'listings/search.html',context)

class ListingsListView(ListView):
    # default object is model_list
    # default template is model_list.html
    paginate_by = 3

    model = Listings
    #to filter data but the default object for class  based view is same
    #queryset = Listings.objects.filter(price__gte=25000)

    template_name = 'listings/listings.html'
   # def get_context_data(self, **kwargs):
     #   object = super().get_context_data(**kwargs)
      #  return object


class ListingsDetailView(DetailView):
    model = Listings
    template_name = 'listings/listing.html'
    #def get_context_data(self, **kwargs):
       # object = super().get_context_data(**kwargs)
       # return object

templates/listings/listing.html
{%extends 'pages/base.html'%}
{%load static%}
{% block content%}

  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{object.title}}</h1>
          <p class="lead">
            <i class="fas fa-map-marker"></i> {{object.city}} {{object.state}}, {{object.zipcode}}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{%url 'listings'%}">Listings</a>
          </li>
          <li class="breadcrumb-item active">{{object.title}}</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      <a href="listings.html" class="btn btn-light mb-4">Back To Listings</a>
      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img src="{{object.photo_main.url }}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">
            <div class="col-md-2">
              <a href="{{ object.photo_1.url }}" data-lightbox="home-images">
                <img src="{{ object.photo_1.url }}" alt="" class="img-fluid">
              </a>
            </div>
            <div class="col-md-2">
              <a href="{{ object.photo_2.url }}" data-lightbox="home-images">
                <img src="{{ object.photo_2.url }}" alt="" class="img-fluid">
              </a>
            </div>
            <div class="col-md-2">
              <a href="{{ object.photo_3.url }}" data-lightbox="home-images">
                <img src="{{ object.photo_3.url }}"alt="" class="img-fluid">
              </a>
            </div>
            <div class="col-md-2">
              <a href="{{ object.photo_4.url }}" data-lightbox="home-images">
                <img src="{{ object.photo_4.url }}" alt="" class="img-fluid">
              </a>
            </div>
            <div class="col-md-2">
              <a href="{{ object.photo_5.url }}" data-lightbox="home-images">
                <img src="{{ object.photo_5.url }}"alt="" class="img-fluid">
              </a>
            </div>
            <div class="col-md-2">
              <a href="{{ object.photo_6.url }}" data-lightbox="home-images">
                <img src="{{ object.photo_6.url }}" alt="" class="img-fluid">
              </a>
            </div>
          </div>
          <!-- Fields -->
          <div class="row mb-5 fields">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-money-bill-alt"></i> Asking Price:
                  <span class="float-right">{{object.price}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Bedrooms:
                  <span class="float-right">{{object.bedrooms}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bath"></i> Bathrooms:
                  <span class="float-right">{{object.bathrooms}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-car"></i> Garage:
                  <span class="float-right">{{object.garage}}
                  </span>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-th-large"></i> Square Feet:
                  <span class="float-right">{{object.sqft}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-square"></i> Lot Size:
                  <span class="float-right">{{object.lot_size}} Acres
                  </span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-calendar"></i> Listing Date:
                  <span class="float-right">{{object.list_date}}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Realtor:
                  <span class="float-right">{{object.realtor}}
                  </span>
                </li>


              </ul>
            </div>
          </div>

          <!-- Description -->
          <div class="row mb-5">
            <div class="col-md-12">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia recusandae esse reiciendis officia omnis non rerum dicta
              cupiditate nostrum molestias deserunt aut minus inventore animi atque, consequuntur ad fugit. Possimus culpa
              blanditiis repellendus ipsa similique ullam, natus error dolor harum.
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3">
            <img class="card-img-top" src="{{object.realtor.photo.url}}" alt="Seller of the month">
            <div class="card-body">
              <h5 class="card-title">Property Realtor</h5>
              <h6 class="text-secondary">{{object.realtor}}</h6>
            </div>
          </div>
          <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
        </div>
      </div>
    </div>
  </section>

  <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url  'contact'%}"method="POST">
            {%csrf_token%}
            {% if  user.is_authenticated %}
            <input type="hidden" name="user_id" value="{{user.id}}">
            {%else%}
            <input type="hidden" name="user_id" value="0">
            {%endif%}
            <input type="hidden" name="realtor_email" value="{{object.realtor.email}}">
            <input type="hidden" name="listing_id" value="{{object.id}}">
            <div class="form-group">
              <label for="property_name" class="col-form-label">Property:</label>
              <input type="text" name="listing" class="form-control" value="{{object.title}}" >
            </div>
            <div class="form-group">
              <label for="name" class="col-form-label">Name:</label>
              <input type="text" name="name" class="form-control"  {% if user.is_authenticated %}  value="{{user.first_name}} {{user.last_name}}"{%endif%} required>
            </div>
            <div class="form-group">
              <label for="email" class="col-form-label">Email:</label>
              <input type="email" name="email" class="form-control" {% if user.is_authenticated %}  value="{{user.email}}"{%endif%} required>
            </div>
            <div class="form-group">
              <label for="phone" class="col-form-label">Phone:</label>
              <input type="text" name="phone" class="form-control">
            </div>
            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="message" class="form-control"></textarea>
            </div>
            <hr>
            <input type="submit" value="Send" class="btn btn-block btn-secondary">
          </form>
        </div>
      </div>
    </div>
  </div>


{% endblock%}

templates/listings/listings.html
{% extends 'pages/base.html'%}
{% load static %}
{% load humanize %}
{% block content%}
    <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Browse Our Properties</h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Browse Listings</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        <!--{% if listings_list %}-->
{% for listing in object_list %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
            <div class="card-img-overlay">
              <h2>
                <span class="badge badge-secondary text-white">{{listing.price|intcomma}}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{listing.title}}</h4>
                <p>
                  <i class="fas fa-map-marker text-secondary"></i> {{listing.city}},{{listing.state}}, {{listing.zipcode}}</p>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}</div>
                <div class="col-6">
                  <i class="fas fa-car"></i> Garage: 2</div>
              </div>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                <div class="col-6">
                  <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-12">
                  <i class="fas fa-user"></i>{{listing.realtor}}</div>
              </div>
              <div class="row text-secondary pb-2">
                <div class="col-6">
                  <i class="fas fa-clock"></i> {{listing.list_date|timesince}}</div>
              </div>
              <hr>
              <a href="{{listing.id}}" class="btn btn-primary btn-block">More Info</a>
            </div>
          </div>
        </div>


{% endfor %}
      <!--  {% else %}
        <div class="col-md-12">
          <p>ni listings available</p>
        {% endif %}-->
<div class="row">
        <div class="col-md-12">
          {% if page_obj.has_other_pages %}
          <ul class="pagination">
            {%if page_obj.has_previous%}
            <li class="page-item active">
              <a class="page-link" href="?page={{page_obj.previous_page_number}}">&laquo;</a>
            </li>
            {%else%}
             <li class="page-item disable">
              <a class="page-link" href="#">&laquo;</a>
            </li>
            {%endif%}
            {%for i in page_obj.paginator.page_range%}
              {%if page_obj.number == i%}
                  <li class="page-item active">
                    <a class="page-link" >{{i}}</a>
                  </li>
            {%else%}
                  <li class="page-item disable">
                    <a class="page-link" href='?page{{i}}'>{{i}}</a>
                  </li>
              {%endif%}
            {%endfor%}
            {%if page_obj.has_next%}
                <li class="page-item active">
                  <a class="page-link" href="?page={{page_obj.next_page_number}}">&raquo;</a>
                </li>
            {%else%}
                 <li class="page-item disable">
                  <a class="page-link" href="#">&raquo;</a>
               {%endif%}
            </li>
          </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/listings/search.html
{%extends 'pages/base.html'%}
{% load static %}
{%load humanize%}
{%block content%}
 <section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <form action="{% url 'search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Keywords</label>
                <input type="text" name="keywords" class="form-control" placeholder="Keyword (Pool, Garage, etc)">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" class="form-control" placeholder="City" value={{values.city}}>
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">State</label>
                <select name="state" class="form-control">
                  <option selected="true" disabled="disabled" value={{values.state}}>State (All)</option>
                     {% for key,value in state_choices.items %}
                      <option value="{{key}}" {%if key == values.state %} selected='true' {%endif%}%}>{{value}}</option>
                     {%endfor%}

                </select>
              </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Bedrooms</label>
                <select name="bedrooms" class="form-control">
                  <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                   {% for key,value in bedroom_choices.items %}
                      <option value="{{key}}" {%if key == values.bedrooms %} selected="true"{%endif%}>{{value}}</option>
                    {%endfor%}
                </select>
                  </div>
                <div class="col-md-6 mb-3">
                <select name="price" class="form-control">
                  <option selected="true" disabled="disabled">Max Price (All)</option>
                    {% for key,value in price_choice.items %}
                        <option value="{{key}}" {%if key == values.price %} selected {%endif%}>{{value}}</option>
                    {%endfor%}
                </select>
              </div>

            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings'%}">Browse Listings</a>
          </li>
          <li class="breadcrumb-item active"> Search Results</li>
        </ol>
      </nav>
    </div>
  </section>

<section id="listings" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Latest Listings</h3>
      <div class="row">
        <!-- Listing 1 -->
{% for listing in listings %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card listing-preview">
            <img class="card-img-top" src={{listing.photo_main.url}} alt="">
            <div class="card-img-overlay">
              <h2>
                <span class="badge badge-secondary text-white">{{listing.price|intcomma}}</span>
              </h2>
            </div>
            <div class="card-body">
              <div class="listing-heading text-center">
                <h4 class="text-primary">{{listing.title}}</h4>
                <p>
                  <i class="fas fa-map-marker text-secondary"></i> {{listing.city}},{{listing.state}},{{listing.zipcode}}</p>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-th-large"></i> Sqft: {{listing.sqft}}</div>
                <div class="col-6">
                  <i class="fas fa-car"></i> Garage: {{listing.garage}}</div>
              </div>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}</div>
                <div class="col-6">
                  <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}</div>
              </div>
              <hr>
              <div class="row py-2 text-secondary">
                <div class="col-6">
                  <i class="fas fa-user"></i> {{listing.realtor}}</div>
              </div>
              <div class="row text-secondary pb-2">
                <div class="col-6">
                  <i class="fas fa-clock"></i> {{listing.list_date|timesince}}</div>
              </div>
              <hr>
              <a href="listings/{{listing.id}} "class="btn btn-primary btn-block">More Info</a>
            </div>
          </div>
        </div>
        {% endfor%}

          </div>
    </div>
  </section>







{%endblock%}